### ISSUE TITLE
Can't find documentation about DQN in this environment 

### ISSUE THREAD

**Issue by Noor59007** [nadavbh12/Retro-Learning-Environment#8]
I run environment through python interface from doc/example like
$ python python_example.py path_to_rom path_to_core
I modified the code set episode to 2000 and the training was running for 1 day but the agent is not learning.
I searched the code but couldn't find the module for DQN.
Please kindly Help.

**Comment by nadavbh12** [comment]
The python example is of a random agent.
To run DQN on RLE, checkout [this repository](https://github.com/nadavbh12/deep_q_rl).

**Comment by Noor59007** [comment]
I wonder if this RLE environment is used to produce the Table 3 in the paper "Playing SNES with RLE" especially for Mortal_Kombat?
If we impose the above mentioned repository to the RLE, should we get the results?

**Comment by nadavbh12** [comment]
The deep_w_rl repository should be able to reproduce the the results for the first column (DQN).
The results in our paper were achieved by running a Torch based agent which supports DQN, DDQN and D-DQN.
However, there are many implementation for DQN around on GitHub. It should be easy to modify them to use RLE rather than ALE as their interface is nearly identical.

Notice that the results for Mortal Kombat were achieved using random initialization at the beginning of each level.
You can set this by calling `SetBool("MK_random_position", True)`.

**Comment by Noor59007** [comment]
Hi @nadavbh12, 

I am working on [this repository](https://github.com/nadavbh12/deep_q_rl) but i got an issue while running this command `pip install --user .` and here is the screen shot:
![screenshot from 2017-01-27 00-27-12](https://cloud.githubusercontent.com/assets/6708048/22337119/8e29a0c2-e427-11e6-8b3b-3a7df81d0c2c.png)

Please guide me where i am going wrong. Thanks

**Comment by nadavbh12** [comment]
Try removing the CMakeCache.txt file from the project's main directory and re-running the command.
I think this should resolve the issue.

**Comment by Noor59007** [comment]
Thanks, I fix this issue, but next when I run this command `./run_nips.py --rom mortal_kombat.sfc --core snes` I got error related to core. Here is my rom directory with rom file. 
![screenshot from 2017-01-27 03-11-20](https://cloud.githubusercontent.com/assets/6708048/22344201/9a12933c-e43e-11e6-836e-fe666a0c9010.png)
And Here is my core directory
![screenshot from 2017-01-27 03-11-40](https://cloud.githubusercontent.com/assets/6708048/22344218/ac118bba-e43e-11e6-86b7-57bcbf6389c0.png)
And here is the output:
![screenshot from 2017-01-27 03-05-47](https://cloud.githubusercontent.com/assets/6708048/22344244/bc6e7e6e-e43e-11e6-884e-506651c087cd.png)
full output is in this file:
[log.txt](https://github.com/nadavbh12/Retro-Learning-Environment/files/733156/log.txt)

**Comment by Noor59007** [comment]
Hi, I have solved the above issue. However, there is another problem now. Attached is the screenshot. 

[screenshot_20170129-025918](https://cloud.githubusercontent.com/assets/6708048/22398648/3de21dec-e5d0-11e6-8a98-a7171974ec70.jpg)

**Comment by nadavbh12** [comment]
Hey @Noor59007,
It seems that your first issue was due to a python installation commit that I'm working on.
I've edited the dependency script in deep_q_rl so that it will get RLE's previous release where the older setup.py script is present.

Regarding the new issue, I was unable to reproduce it.
Did you modify the files in deep_q_rl?
Could you check the dimensions of the screen_buffer as returned from the interface in ale_experiment.py line 120?

**Comment by Noor59007** [comment]
Yeah, there was some path issues for the core file, So, we modified it somehow. 
I found out these dimensions. [256, 224]
However, the error is still existing. 
![error](https://cloud.githubusercontent.com/assets/6708048/22405868/376b62fe-e68c-11e6-94e0-1d4bbd1ae8e6.png)

**Comment by nadavbh12** [comment]
84x84 is the cropped image size.
It seems that for some reason your image is only 10x84.
Try following the image object with a debugger and see when its size changes. 
Since I wasn't able to reproduce this and the image size is as expected, a wild guess would be to check your numpy is updated and working correctly.

If that doesn't work, try running the original atari version of deep_q_rl so we're sure the problem is with my fork rather than your setup.
